package generator

type GoFile struct {
	SkipDoNotEdit bool
	PackageName   string
	Imports       []string
	Body          Templater
}

var tmGoFile = InitTemplate("GoFile", `
{{- if not .SkipDoNotEdit }}// Code generated by goag (https://github.com/vkd/goag). DO NOT EDIT.{{ end }}
package {{ .PackageName }}

{{ if .Imports -}}
import (
	{{ range $_, $i := .Imports }}
	"{{ $i }}"
	{{- end }}
)
{{- end }}

{{ exec .Body }}
`)

func (g GoFile) Execute() (string, error) { return tmGoFile.Execute(g) }
