// Code generated by goag (https://github.com/vkd/goag). DO NOT EDIT.
package test

import (
	"context"
	"fmt"
	"net/http"
	"strings"
)

type API struct {
	ListPetsHandler    ListPetsHandlerFunc
	CreatePetsHandler  CreatePetsHandlerFunc
	ShowPetByIDHandler ShowPetByIDHandlerFunc

	// not found
	NotFoundHandler http.Handler
	// spec file
	SpecFileHandler http.Handler

	Middlewares []func(h http.Handler) http.Handler
}

func (rt *API) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	path := r.URL.Path

	if rt.SpecFileHandler != nil && path == "/v1/openapi.yaml" {
		rt.SpecFileHandler.ServeHTTP(rw, r)
		return
	}

	h, r := rt.Route(r)
	if h == nil {
		h = rt.NotFoundHandler
		if h == nil {
			h = http.NotFoundHandler()
		}
		h.ServeHTTP(rw, r)
		return
	}

	for i := len(rt.Middlewares) - 1; i >= 0; i-- {
		h = rt.Middlewares[i](h)
	}
	h.ServeHTTP(rw, r)
}

func (rt *API) Route(r *http.Request) (http.Handler, *http.Request) {
	h, path := rt.route(r.URL.Path, r.Method)
	if h == nil {
		return nil, r
	}

	r = r.WithContext(context.WithValue(r.Context(), pathKey{}, path))
	return h, r
}

func (rt *API) route(path, method string) (http.Handler, string) {
	if !strings.HasPrefix(path, "/v1") {
		return nil, ""
	}
	path = path[3:] // "/v1"

	if !strings.HasPrefix(path, "/") {
		return nil, ""
	}

	prefix, path := splitPath(path)

	if path == "" {
		switch prefix {
		case "/pets":
			switch method {
			case http.MethodGet:
				h := http.Handler(rt.ListPetsHandler)
				return h, "/pets"
			case http.MethodPost:
				h := http.Handler(rt.CreatePetsHandler)
				return h, "/pets"
			}
		}
		return nil, ""
	}

	switch prefix {
	case "/pets":
		return rt.routePets(path, method)
	}
	return nil, ""
}

func (rt *API) routePets(path, method string) (http.Handler, string) {
	_, path = splitPath(path)

	if path == "" {

		switch method {
		case http.MethodGet:
			h := http.Handler(rt.ShowPetByIDHandler)
			return h, "/pets/{petId}"
		}
		return nil, ""
	}

	return nil, ""
}

type pathKey struct{}

func SchemaPath(r *http.Request) (string, bool) {
	if s, ok := r.Context().Value(pathKey{}).(string); ok {
		return s, true
	}
	return r.URL.Path, false
}

var specFileBs = []byte(SpecFile)

func SpecFileHandler() http.Handler {
	return http.HandlerFunc(func(rw http.ResponseWriter, r *http.Request) {
		rw.Header().Set("Content-Type", "application/yaml")
		rw.WriteHeader(http.StatusOK)
		_, err := rw.Write(specFileBs)
		if err != nil {
			LogError(fmt.Errorf("serve spec file: %w", err))
		}
	})
}

func splitPath(s string) (string, string) {
	if !strings.HasPrefix(s, "/") {
		return s, ""
	}
	idx := strings.Index(s[1:], "/")
	if idx == -1 {
		return s, ""
	}
	return s[:idx+1], s[idx+1:]
}
